### ISSUE TITLE
System tray icons for Bluetooth and Networks are shared in Plasma 6

### ISSUE THREAD

**Issue by Dirleye** [CachyOS/char-white#2]
![Screenshot_20240307_183212](https://github.com/CachyOS/char-white/assets/69789934/56ce31eb-d88c-49bc-994b-f2f8431d3b6a)
The first icon here is for Bluetooth, the third for Networks.

**Comment by ptr1337** [comment]
> ![Screenshot_20240307_183212](https://private-user-images.githubusercontent.com/69789934/310997635-56ce31eb-d88c-49bc-994b-f2f8431d3b6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzcwMjQsIm5iZiI6MTcwOTgzNjcyNCwicGF0aCI6Ii82OTc4OTkzNC8zMTA5OTc2MzUtNTZjZTMxZWItZDg4Yy00OWJjLTk5NGItZjJmODQzMWQzYjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE4Mzg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNzAwMjBiYzk2YmRmOWU3ZTVjMDRiODc4ZmQ0ZDhlNDUzMTk0ODI0ZjFhNTI2NTRjMThlODhlYTc2ZTIyZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xFLDewvLLHDQJNR_U8uAy0nu1f6lmy3tHW8GBSRLshE) The first icon here is for Bluetooth, the third for Networks.

Yes, the icons needs to be adjusted for Plasma 6.
Maybe @ddh4r4m finds some time for it.
